//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_MANAGER_PROJECTFSOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKYGOITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANGKYGOITAP()
        {
            this.THETHANHVIENs = new HashSet<THETHANHVIEN>();
        }
    
        public int MaDangKyGoiTap { get; set; }
        public Nullable<System.DateTime> NgayDangKi { get; set; }
        public Nullable<decimal> GiaDangKi { get; set; }
        public Nullable<int> MaGoiTap { get; set; }
    
        public virtual GOITAP GOITAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THETHANHVIEN> THETHANHVIENs { get; set; }
    }
}
