//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_MANAGER_PROJECTFSOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GOITAP()
        {
            this.DANGKYGOITAPs = new HashSet<DANGKYGOITAP>();
            this.GIAMGIAs = new HashSet<GIAMGIA>();
        }
    
        public int MaGoiTap { get; set; }
        public Nullable<int> MaDichVu { get; set; }
        public string TenGoiTap { get; set; }
        public Nullable<int> ThoiHanGoiTap { get; set; }
        public Nullable<decimal> GiaGoiTap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGKYGOITAP> DANGKYGOITAPs { get; set; }
        public virtual DICHVU DICHVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAMGIA> GIAMGIAs { get; set; }
    }
}
