//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_MANAGER_PROJECTFSOFT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GYM_ManangerEntities : DbContext
    {
        public GYM_ManangerEntities()
            : base("name=GYM_ManangerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BLOG> BLOGs { get; set; }
        public virtual DbSet<CLUB> CLUBs { get; set; }
        public virtual DbSet<DANGKYGOITAP> DANGKYGOITAPs { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<GIAMGIA> GIAMGIAs { get; set; }
        public virtual DbSet<GOITAP> GOITAPs { get; set; }
        public virtual DbSet<KHOTHIETBI> KHOTHIETBIs { get; set; }
        public virtual DbSet<LOAIBLOG> LOAIBLOGs { get; set; }
        public virtual DbSet<LOAITHETHANHVIEN> LOAITHETHANHVIENs { get; set; }
        public virtual DbSet<LOAITHIETBI> LOAITHIETBIs { get; set; }
        public virtual DbSet<NHAPTHIETBI> NHAPTHIETBIs { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<THANHVIEN> THANHVIENs { get; set; }
        public virtual DbSet<THETHANHVIEN> THETHANHVIENs { get; set; }
        public virtual DbSet<THIETBI> THIETBIs { get; set; }
    }
}
