//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_MANAGER_PROJECTFSOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOTHIETBI
    {
        public int MaThietBiTrongKho { get; set; }
        public Nullable<int> MaThietBi { get; set; }
        public Nullable<int> MaYeuCauNhap { get; set; }
        public Nullable<bool> TrangThaiTonKho { get; set; }
    
        public virtual THIETBI THIETBI { get; set; }
        public virtual NHAPTHIETBI NHAPTHIETBI { get; set; }
    }
}
