//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_MANAGER_PROJECTFSOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITHETHANHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAITHETHANHVIEN()
        {
            this.THETHANHVIENs = new HashSet<THETHANHVIEN>();
        }
    
        public int MaLoaiTheThanhVien { get; set; }
        public string TenLoai { get; set; }
        public Nullable<int> UuDai { get; set; }
        public string HinhAnhThe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THETHANHVIEN> THETHANHVIENs { get; set; }
    }
}
