//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_MANAGER_PROJECTFSOFT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TAIKHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.NHAPTHIETBIs = new HashSet<NHAPTHIETBI>();
            this.Profiles = new HashSet<Profile>();
        }
    
        public int MaTaiKhoan { get; set; }
        [Display(Name = "Account:")]
        public string TaiKhoan1 { get; set; }
        [Display(Name = "Email:")]
        public string Email { get; set; }
        [Display(Name = "Password:")]
        public string MatKhau { get; set; }
        public Nullable<bool> Role { get; set; }
        [Display(Name = "Phone Number:")]
        public string SoDienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHAPTHIETBI> NHAPTHIETBIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile> Profiles { get; set; }
    }
}
