//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_MANAGER_PROJECTFSOFT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIETBI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THIETBI()
        {
            this.KHOTHIETBIs = new HashSet<KHOTHIETBI>();
        }
    
        public int MaThietBi { get; set; }
        public string TenThietBi { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<int> MaLoaiThietBi { get; set; }
        public Nullable<System.DateTime> NgayNhapThietBi { get; set; }
        public Nullable<bool> TrangThaiThietBi { get; set; }
        public string HinhThietBi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOTHIETBI> KHOTHIETBIs { get; set; }
        public virtual LOAITHIETBI LOAITHIETBI { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
